// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdZstyKdOGFS79tcyjlBbi7DnaAyVvM9M',
    appId: '1:7043237208:web:3d752af3ea91c8a7dc112d',
    messagingSenderId: '7043237208',
    projectId: 'event-124e1',
    authDomain: 'event-124e1.firebaseapp.com',
    storageBucket: 'event-124e1.firebasestorage.app',
    measurementId: 'G-8GZZJJ0RGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB02U1h5WKNA0Hpazn9cdipzc5z-tNznyE',
    appId: '1:7043237208:android:f6a549ba79d8deaadc112d',
    messagingSenderId: '7043237208',
    projectId: 'event-124e1',
    storageBucket: 'event-124e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMD4-leloBe3nTiLCK7NdoJ7pOGAuBMw',
    appId: '1:7043237208:ios:6afc33ff2dd7a4fddc112d',
    messagingSenderId: '7043237208',
    projectId: 'event-124e1',
    storageBucket: 'event-124e1.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgMD4-leloBe3nTiLCK7NdoJ7pOGAuBMw',
    appId: '1:7043237208:ios:6afc33ff2dd7a4fddc112d',
    messagingSenderId: '7043237208',
    projectId: 'event-124e1',
    storageBucket: 'event-124e1.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdZstyKdOGFS79tcyjlBbi7DnaAyVvM9M',
    appId: '1:7043237208:web:301fccccabda925fdc112d',
    messagingSenderId: '7043237208',
    projectId: 'event-124e1',
    authDomain: 'event-124e1.firebaseapp.com',
    storageBucket: 'event-124e1.firebasestorage.app',
    measurementId: 'G-PJJPJNEYTK',
  );
}
